#!/usr/bin/python3
# -*- coding: UTF-8 -*-
#
#########################################################
# Name: audiomass launcher
# Porpose: run audiomass module
# Platform: Mac OsX, Gnu/Linux
# Writer: jeanslack <jeanlucperni@gmail.com>
# license: GPL3
# Rev: Aug 8 2018
#########################################################

from admspack import main_prg
main_prg.main()
