#!/usr/bin/python
# -*- coding: UTF-8 -*-
#
#########################################################
# Name: audiomass (main script)
# Porpose:  launch audiomass script for command line interface
# Writer: Gianluca Pernigoto <jeanlucperni@gmail.com>
# Copyright: (c) 2015/2016 Gianluca Pernigoto <jeanlucperni@gmail.com>
# license: GPL3
# Version: (Ver.0.6) Febbruary 2015
# Rev
#########################################################

import sys
import os
from admspack.datastrings import usage, copying, version
from admspack.getcommand import batch_, single_

def main():
    """
    Verify the arguments passed on the command line interface.
    """
    if '-b' in sys.argv or '--batch' in sys.argv: 
        try:
            if os.path.isdir(sys.argv[2]): 
                path_in = sys.argv[2] # this is a dir-name (if not empty)
            else:
                usage()
                sys.exit('\n\033[1m Error:\033[0m Invalid path-name\n')
        except IndexError:
            path_in = os.getcwd() # if no dir-name use current work directory

        batch_(path_in)

    elif '-v' in sys.argv or '--version' in sys.argv:
        print version(); sys.exit()
        
    elif '-h' in sys.argv or '--help' in sys.argv:
        usage(); sys.exit()
        
    elif '-c' in sys.argv or '--copying' in sys.argv:
        copying(); sys.exit()

    else:
        try:
            if os.path.isfile(sys.argv[1]): # must be file only here
                path_in = sys.argv[1] # is a file-name
            else:
                usage()
                sys.exit('\n\033[1m Error:\033[0m Invalid file-name\n')
        except IndexError:
            usage()
            sys.exit('\033[1m Error:\033[0m must be a file\n')

        # input_format is the extension format of path_in

        input_format = os.path.splitext(path_in)[1].replace(".","")
        single_(input_format, path_in)
    
    return 0

if __name__ == '__main__':
    status = main()
    sys.exit(status)
