#!/usr/bin/python3
# -*- coding: UTF-8 -*-

def graphic_menu():
    """
    Menu for output audio selection format used from all process(f,d,b)
    """
    return [
    "------------",
    " \033[1m 1 \033[0m> Wav   (WAVEform audio format, PCM uncompresed)", 
    " \033[1m 2 \033[0m> Aiff  (Apple Interchange File Format)", 
    " \033[1m 3 \033[0m> Flac  (Free Lossless Audio Codecs)", 
    " \033[1m 4 \033[0m> Ape   (Monkey's audio)", 
    " \033[1m 5 \033[0m> Mp3   (MPEG-1 Audio Layer 3)", 
    " \033[1m 6 \033[0m> Ogg   (ogg-vorbis lossy format)",  
    "------------", 
    " \033[41;37;1m A \033[0m \033[1m..ABORT\033[0m", 
    "------------"]

def supported_formats():
  """
  supported_format: it is useful to limit the choices within 
  the available options of the graphic_menu.
  Set the list in the graphic_menu with the appropriate formats indexes
  """
  return {'1': (1,'WAV','wav',[1]), '2': (2,'AIFF','aiff',[2]), 
          '3': (3,'FLAC','flac',[3]), '4': (4,'APE','ape',[3,4]), 
          '5': (5,'MP3','mp3',[3,4,5,6]),'6': (6,'OGG','ogg',[3,4,5,6])
          }

input_format = 'wav'
new = graphic_menu()[:]

for v in supported_formats().values():
    if input_format in v[1:3]:
        print('si')
        new = [ new[i] for i in range(len(new)) if i not in set(v[3]) ]
#print(new)

for outformat in new:# realizzazione menu di output
    print ("    %s" % outformat)
output_selection = input("    Type a number corresponding"
                                            " format and press enter key... ")